{
 "title": "Sock Shop",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "time", "query": "1m" },
   {
    "name": "deploy",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"sock-shop\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Req/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (destination_workload) (rate(istio_requests_total{namespace=\"sock-shop\", source_workload=\"istio-ingress\", destination_workload=\"front-end\", response_code!~\"5.*|4.*\", reporter=\"destination\"}[$time]))",
     "legendFormat": "istio-proxy [200]"
    },
    {
     "expr": "sum by (destination_workload) (rate(istio_requests_total{namespace=\"sock-shop\", source_workload=\"istio-ingress\", destination_workload=\"front-end\", response_code=~\"5.*|4.*\", reporter=\"destination\"}[$time]))",
     "legendFormat": "istio-proxy [500]"
    }
   ]
  },
  {
   "title": "Average delay [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (destination_workload) (increase(istio_request_duration_milliseconds_sum{namespace=\"sock-shop\", source_workload=\"istio-ingress\", destination_workload=\"front-end\", response_code!~\"5.*|4.*\", response_flags=\"-\", reporter=\"destination\"}[$time]))\n/\nsum by (destination_workload) (increase(istio_request_duration_milliseconds_count{namespace=\"sock-shop\", source_workload=\"istio-ingress\", destination_workload=\"front-end\", response_code!~\"5.*|4.*\", response_flags=\"-\", reporter=\"destination\"}[$time]))",
     "legendFormat": "front-end"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"sock-shop\"}",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"istio-ingress\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "P95",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", destination_canonical_service=~\"front-end\"}[$time]))\n  by (\n    destination_canonical_service,\n    destination_workload_namespace,\n    source_canonical_service,\n    source_workload_namespace,\n    le\n  )\n)\n",
     "legendFormat": "{{destination_canonical_service}}"
    }
   ]
  },
  {
   "title": "CPU (%) [all]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "(\nsum by (container) (rate(container_cpu_usage_seconds_total{namespace=\"sock-shop\", container!=\"istio-proxy\", container!=\"\"}[$time]))\n/\nsum by (container) (kube_pod_container_resource_limits{namespace=\"sock-shop\", resource=\"cpu\", container!=\"istio-proxy\"})\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU (%) [$deploy]",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 22 },
   "repeat": "deploy",
   "targets": [
    {
     "expr": "(\nsum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"sock-shop\", container!=\"istio-proxy\", container!=\"\", pod=~\"$deploy.*\"}[$time]))\n/\nsum by (pod) (kube_pod_container_resource_limits{namespace=\"sock-shop\", resource=\"cpu\", container!=\"istio-proxy\", pod=~\"$deploy.*\"})\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}