---
apiVersion: v1
kind: Service
metadata:
  name: carts-target
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: carts
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      appProtocol: http
  selector:
    app: carts
---
apiVersion: mubench.com/v1alpha1
kind: ProxyService
metadata:
  name: carts-proxy
  namespace: sock-shop
spec:
  serviceName: carts
  loadBalancer: LEAST_REQUEST
  target: carts-target
  port: 80
# ---
# apiVersion: networking.istio.io/v1beta1
# kind: DestinationRule
# metadata:
#   name: carts
# spec:
#     host: carts
#     trafficPolicy:
#       loadBalancer:
#         simple: LEAST_REQUEST