---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-target
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: catalogue
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      appProtocol: http
  selector:
    app: catalogue
---
apiVersion: msvcbench.io/v1alpha1
kind: ProxyService
metadata:
  name: catalogue-proxy
  namespace: sock-shop
spec:
  serviceName: catalogue
  loadBalancer: LEAST_REQUEST
  target: catalogue-target
  port: 80
# ---
# apiVersion: networking.istio.io/v1beta1
# kind: DestinationRule
# metadata:
#   name: catalogue
# spec:
#     host: catalogue
#     trafficPolicy:
#       loadBalancer:
#         simple: LEAST_REQUEST