apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: proxyservices.msvcbench.io
spec:
  group: msvcbench.io
  scope: Namespaced
  names:
    plural: proxyservices
    singular: proxyservice
    kind: ProxyService
    shortNames:
    - ps
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serviceName:
                  type: string
                  description: The name of the service of the proxy service.
                target:
                  type: string
                  description: The target service of the proxy service.
                loadBalancer:
                  type: string
                  description: The type of load balancer to use.
                protocol:
                  type: string
                  description: The protocol of the target service.
                port:
                  type: integer
                  description: The port of the target service.
                uri:
                  type: object
                  properties:
                    matchUriPrefix:
                      type: string
                      description: The URI prefix to match.
                    rewriteUri:
                      type: string
                      description: The URI to rewrite to.
