---
# Source: gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ my-ingress-name }}
  namespace: {{ namespace }}
  labels:
    app: {{ my-ingress-name }}
    istio: {{ my-ingress-name }}
    app.kubernetes.io/name: {{ my-ingress-name }}
---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ my-ingress-name }}
  namespace: {{ namespace }}
  labels:
    app: {{ my-ingress-name }}
    istio: {{ my-ingress-name }}
    app.kubernetes.io/name: {{ my-ingress-name }}
  annotations:
    {}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ my-ingress-name }}
  namespace: {{ namespace }}
  labels:
    app: {{ my-ingress-name }}
    istio: {{ my-ingress-name }}
    app.kubernetes.io/name: {{ my-ingress-name }}
  annotations:
    {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ my-ingress-name }}
subjects:
- kind: ServiceAccount
  name: {{ my-ingress-name }}
---
# Source: gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ my-service-name }}
  namespace: {{ namespace }}
  labels:
    app: {{ my-ingress-name }}
    istio: {{ my-ingress-name }}
    app.kubernetes.io/name: {{ my-ingress-name }}
  annotations:
    {}
spec:
  type: NodePort
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: {{ port }}
      protocol: TCP
      targetPort: {{ port }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: {{ my-ingress-name }}
    istio: {{ my-ingress-name }}
  
---
# Source: gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ my-ingress-name }}
  namespace: {{ namespace }}
  labels:
    app: {{ my-ingress-name }}
    istio: {{ my-ingress-name }}
    app.kubernetes.io/name: {{ my-ingress-name }}
  annotations:
    {}
spec:
  selector:
    matchLabels:
      app: {{ my-ingress-name }}
      istio: {{ my-ingress-name }}
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      labels:
        sidecar.istio.io/inject: "true"
        app: {{ my-ingress-name }}
        istio: {{ my-ingress-name }}
    spec:
      serviceAccountName: {{ my-ingress-name }}
      securityContext:
        # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      containers:
        - name: istio-proxy
          # "auto" will be populated at runtime by the mutating webhook. See https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection
          image: auto
          securityContext:
            # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
            capabilities:
              drop:
              - ALL
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1337
            runAsGroup: 1337
            runAsNonRoot: true
          env:
          ports:
          - containerPort: 15090
            protocol: TCP
            name: http-envoy-prom
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
      terminationGracePeriodSeconds: 30
# ---
# Source: gateway/templates/hpa.yaml
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: {{ my-ingress-name }}
#   namespace: {{ namespace }}
#   labels:
#     app: {{ my-ingress-name }}
#     istio: {{ my-ingress-name }}
#     app.kubernetes.io/name: {{ my-ingress-name }}
#   annotations:
#     {}
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: {{ my-ingress-name }}
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           averageUtilization: 80
#           type: Utilization
